version: '3.9'

services:
    postgres:
        image: postgres:14.1-alpine
        env_file:
            - ./.env
        container_name: ${POSTGRES_CONTAINER}
        environment:
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        restart: always

volumes:
    pg_data: {}
